//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class actualizacion
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string nombre_tabla { get; set; }
        public string registro { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
    }
}
