//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public ciudad()
        {
            this.municipios = new HashSet<municipio>();
        }
    
        public int clavec { get; set; }
        public string nombrec { get; set; }
    
        public virtual ICollection<municipio> municipios { get; set; }
    }
}
