//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp
    {
        public cp()
        {
            this.colonias = new HashSet<colonia>();
        }
    
        public int clavec { get; set; }
        public Nullable<int> clavemfk { get; set; }
    
        public virtual ICollection<colonia> colonias { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
