//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("kosmozbusModel", "departamento_ibfk_1", "empresaservicio", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.empresaservicio), "departamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.departamento), true)]
[assembly: EdmRelationshipAttribute("kosmozbusModel", "trabajador_ibfk_1", "departamento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.departamento), "trabajador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.trabajador), true)]
[assembly: EdmRelationshipAttribute("kosmozbusModel", "usuario_ibfk_1", "trabajador", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.trabajador), "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.usuario), true)]

#endregion

namespace DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class kosmozbusEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new kosmozbusEntities object using the connection string found in the 'kosmozbusEntities' section of the application configuration file.
        /// </summary>
        public kosmozbusEntities() : base("name=kosmozbusEntities", "kosmozbusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kosmozbusEntities object.
        /// </summary>
        public kosmozbusEntities(string connectionString) : base(connectionString, "kosmozbusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kosmozbusEntities object.
        /// </summary>
        public kosmozbusEntities(EntityConnection connection) : base(connection, "kosmozbusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<actualizacion> actualizacions
        {
            get
            {
                if ((_actualizacions == null))
                {
                    _actualizacions = base.CreateObjectSet<actualizacion>("actualizacions");
                }
                return _actualizacions;
            }
        }
        private ObjectSet<actualizacion> _actualizacions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<departamento> departamentoes
        {
            get
            {
                if ((_departamentoes == null))
                {
                    _departamentoes = base.CreateObjectSet<departamento>("departamentoes");
                }
                return _departamentoes;
            }
        }
        private ObjectSet<departamento> _departamentoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<empresaservicio> empresaservicios
        {
            get
            {
                if ((_empresaservicios == null))
                {
                    _empresaservicios = base.CreateObjectSet<empresaservicio>("empresaservicios");
                }
                return _empresaservicios;
            }
        }
        private ObjectSet<empresaservicio> _empresaservicios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<log> logs
        {
            get
            {
                if ((_logs == null))
                {
                    _logs = base.CreateObjectSet<log>("logs");
                }
                return _logs;
            }
        }
        private ObjectSet<log> _logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rol> rols
        {
            get
            {
                if ((_rols == null))
                {
                    _rols = base.CreateObjectSet<rol>("rols");
                }
                return _rols;
            }
        }
        private ObjectSet<rol> _rols;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<trabajador> trabajadors
        {
            get
            {
                if ((_trabajadors == null))
                {
                    _trabajadors = base.CreateObjectSet<trabajador>("trabajadors");
                }
                return _trabajadors;
            }
        }
        private ObjectSet<trabajador> _trabajadors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuario>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuario> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the actualizacions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToactualizacions(actualizacion actualizacion)
        {
            base.AddObject("actualizacions", actualizacion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the departamentoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepartamentoes(departamento departamento)
        {
            base.AddObject("departamentoes", departamento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the empresaservicios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToempresaservicios(empresaservicio empresaservicio)
        {
            base.AddObject("empresaservicios", empresaservicio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologs(log log)
        {
            base.AddObject("logs", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rols EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorols(rol rol)
        {
            base.AddObject("rols", rol);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the trabajadors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotrabajadors(trabajador trabajador)
        {
            base.AddObject("trabajadors", trabajador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuario usuario)
        {
            base.AddObject("usuarios", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="actualizacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class actualizacion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new actualizacion object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static actualizacion Createactualizacion(global::System.Int32 id)
        {
            actualizacion actualizacion = new actualizacion();
            actualizacion.id = id;
            return actualizacion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true, "usuario");
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_tabla
        {
            get
            {
                return _nombre_tabla;
            }
            set
            {
                Onnombre_tablaChanging(value);
                ReportPropertyChanging("nombre_tabla");
                _nombre_tabla = StructuralObject.SetValidValue(value, true, "nombre_tabla");
                ReportPropertyChanged("nombre_tabla");
                Onnombre_tablaChanged();
            }
        }
        private global::System.String _nombre_tabla;
        partial void Onnombre_tablaChanging(global::System.String value);
        partial void Onnombre_tablaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String registro
        {
            get
            {
                return _registro;
            }
            set
            {
                OnregistroChanging(value);
                ReportPropertyChanging("registro");
                _registro = StructuralObject.SetValidValue(value, true, "registro");
                ReportPropertyChanged("registro");
                OnregistroChanged();
            }
        }
        private global::System.String _registro;
        partial void OnregistroChanging(global::System.String value);
        partial void OnregistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> hora
        {
            get
            {
                return _hora;
            }
            set
            {
                OnhoraChanging(value);
                ReportPropertyChanging("hora");
                _hora = StructuralObject.SetValidValue(value, "hora");
                ReportPropertyChanged("hora");
                OnhoraChanged();
            }
        }
        private Nullable<global::System.DateTime> _hora;
        partial void OnhoraChanging(Nullable<global::System.DateTime> value);
        partial void OnhoraChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="departamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class departamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new departamento object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static departamento Createdepartamento(global::System.Int32 id)
        {
            departamento departamento = new departamento();
            departamento.id = id;
            return departamento;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idempresafk
        {
            get
            {
                return _idempresafk;
            }
            set
            {
                OnidempresafkChanging(value);
                ReportPropertyChanging("idempresafk");
                _idempresafk = StructuralObject.SetValidValue(value, "idempresafk");
                ReportPropertyChanged("idempresafk");
                OnidempresafkChanged();
            }
        }
        private Nullable<global::System.Int32> _idempresafk;
        partial void OnidempresafkChanging(Nullable<global::System.Int32> value);
        partial void OnidempresafkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String no_departamento
        {
            get
            {
                return _no_departamento;
            }
            set
            {
                Onno_departamentoChanging(value);
                ReportPropertyChanging("no_departamento");
                _no_departamento = StructuralObject.SetValidValue(value, true, "no_departamento");
                ReportPropertyChanged("no_departamento");
                Onno_departamentoChanged();
            }
        }
        private global::System.String _no_departamento;
        partial void Onno_departamentoChanging(global::System.String value);
        partial void Onno_departamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_corto
        {
            get
            {
                return _nombre_corto;
            }
            set
            {
                Onnombre_cortoChanging(value);
                ReportPropertyChanging("nombre_corto");
                _nombre_corto = StructuralObject.SetValidValue(value, true, "nombre_corto");
                ReportPropertyChanged("nombre_corto");
                Onnombre_cortoChanged();
            }
        }
        private global::System.String _nombre_corto;
        partial void Onnombre_cortoChanging(global::System.String value);
        partial void Onnombre_cortoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagen
        {
            get
            {
                return _imagen;
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, true, "imagen");
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.String _imagen;
        partial void OnimagenChanging(global::System.String value);
        partial void OnimagenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value, "fecha_creacion");
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_creacion;
        partial void Onfecha_creacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_creacionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kosmozbusModel", "departamento_ibfk_1", "empresaservicio")]
        public empresaservicio empresaservicio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresaservicio>("kosmozbusModel.departamento_ibfk_1", "empresaservicio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresaservicio>("kosmozbusModel.departamento_ibfk_1", "empresaservicio").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<empresaservicio> empresaservicioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresaservicio>("kosmozbusModel.departamento_ibfk_1", "empresaservicio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<empresaservicio>("kosmozbusModel.departamento_ibfk_1", "empresaservicio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kosmozbusModel", "trabajador_ibfk_1", "trabajador")]
        public EntityCollection<trabajador> trabajadors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<trabajador>("kosmozbusModel.trabajador_ibfk_1", "trabajador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<trabajador>("kosmozbusModel.trabajador_ibfk_1", "trabajador", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="empresaservicio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empresaservicio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new empresaservicio object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static empresaservicio Createempresaservicio(global::System.Int32 id)
        {
            empresaservicio empresaservicio = new empresaservicio();
            empresaservicio.id = id;
            return empresaservicio;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_corto
        {
            get
            {
                return _nombre_corto;
            }
            set
            {
                Onnombre_cortoChanging(value);
                ReportPropertyChanging("nombre_corto");
                _nombre_corto = StructuralObject.SetValidValue(value, true, "nombre_corto");
                ReportPropertyChanged("nombre_corto");
                Onnombre_cortoChanged();
            }
        }
        private global::System.String _nombre_corto;
        partial void Onnombre_cortoChanging(global::System.String value);
        partial void Onnombre_cortoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cabezera
        {
            get
            {
                return _cabezera;
            }
            set
            {
                OncabezeraChanging(value);
                ReportPropertyChanging("cabezera");
                _cabezera = StructuralObject.SetValidValue(value, true, "cabezera");
                ReportPropertyChanged("cabezera");
                OncabezeraChanged();
            }
        }
        private global::System.String _cabezera;
        partial void OncabezeraChanging(global::System.String value);
        partial void OncabezeraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagen
        {
            get
            {
                return _imagen;
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, true, "imagen");
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.String _imagen;
        partial void OnimagenChanging(global::System.String value);
        partial void OnimagenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value, "fecha_creacion");
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_creacion;
        partial void Onfecha_creacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_creacionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kosmozbusModel", "departamento_ibfk_1", "departamento")]
        public EntityCollection<departamento> departamentoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<departamento>("kosmozbusModel.departamento_ibfk_1", "departamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<departamento>("kosmozbusModel.departamento_ibfk_1", "departamento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new log object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static log Createlog(global::System.Int32 id)
        {
            log log = new log();
            log.id = id;
            return log;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value, "fecha");
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha;
        partial void OnfechaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true, "usuario");
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tabla
        {
            get
            {
                return _tabla;
            }
            set
            {
                OntablaChanging(value);
                ReportPropertyChanging("tabla");
                _tabla = StructuralObject.SetValidValue(value, true, "tabla");
                ReportPropertyChanged("tabla");
                OntablaChanged();
            }
        }
        private global::System.String _tabla;
        partial void OntablaChanging(global::System.String value);
        partial void OntablaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String operacion
        {
            get
            {
                return _operacion;
            }
            set
            {
                OnoperacionChanging(value);
                ReportPropertyChanging("operacion");
                _operacion = StructuralObject.SetValidValue(value, true, "operacion");
                ReportPropertyChanged("operacion");
                OnoperacionChanged();
            }
        }
        private global::System.String _operacion;
        partial void OnoperacionChanging(global::System.String value);
        partial void OnoperacionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="rol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rol object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static rol Createrol(global::System.Int32 id)
        {
            rol rol = new rol();
            rol.id = id;
            return rol;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true, "descripcion");
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_creaccion
        {
            get
            {
                return _fecha_creaccion;
            }
            set
            {
                Onfecha_creaccionChanging(value);
                ReportPropertyChanging("fecha_creaccion");
                _fecha_creaccion = StructuralObject.SetValidValue(value, "fecha_creaccion");
                ReportPropertyChanged("fecha_creaccion");
                Onfecha_creaccionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_creaccion;
        partial void Onfecha_creaccionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_creaccionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="trabajador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class trabajador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new trabajador object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static trabajador Createtrabajador(global::System.Int32 id)
        {
            trabajador trabajador = new trabajador();
            trabajador.id = id;
            return trabajador;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iddepartamentofk
        {
            get
            {
                return _iddepartamentofk;
            }
            set
            {
                OniddepartamentofkChanging(value);
                ReportPropertyChanging("iddepartamentofk");
                _iddepartamentofk = StructuralObject.SetValidValue(value, "iddepartamentofk");
                ReportPropertyChanged("iddepartamentofk");
                OniddepartamentofkChanged();
            }
        }
        private Nullable<global::System.Int32> _iddepartamentofk;
        partial void OniddepartamentofkChanging(Nullable<global::System.Int32> value);
        partial void OniddepartamentofkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String edad
        {
            get
            {
                return _edad;
            }
            set
            {
                OnedadChanging(value);
                ReportPropertyChanging("edad");
                _edad = StructuralObject.SetValidValue(value, true, "edad");
                ReportPropertyChanged("edad");
                OnedadChanged();
            }
        }
        private global::System.String _edad;
        partial void OnedadChanging(global::System.String value);
        partial void OnedadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String genero
        {
            get
            {
                return _genero;
            }
            set
            {
                OngeneroChanging(value);
                ReportPropertyChanging("genero");
                _genero = StructuralObject.SetValidValue(value, true, "genero");
                ReportPropertyChanged("genero");
                OngeneroChanged();
            }
        }
        private global::System.String _genero;
        partial void OngeneroChanging(global::System.String value);
        partial void OngeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true, "direccion");
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true, "telefono");
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_empleado
        {
            get
            {
                return _numero_empleado;
            }
            set
            {
                Onnumero_empleadoChanging(value);
                ReportPropertyChanging("numero_empleado");
                _numero_empleado = StructuralObject.SetValidValue(value, true, "numero_empleado");
                ReportPropertyChanged("numero_empleado");
                Onnumero_empleadoChanged();
            }
        }
        private global::System.String _numero_empleado;
        partial void Onnumero_empleadoChanging(global::System.String value);
        partial void Onnumero_empleadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cargo
        {
            get
            {
                return _cargo;
            }
            set
            {
                OncargoChanging(value);
                ReportPropertyChanging("cargo");
                _cargo = StructuralObject.SetValidValue(value, true, "cargo");
                ReportPropertyChanged("cargo");
                OncargoChanged();
            }
        }
        private global::System.String _cargo;
        partial void OncargoChanging(global::System.String value);
        partial void OncargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagen
        {
            get
            {
                return _imagen;
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, true, "imagen");
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.String _imagen;
        partial void OnimagenChanging(global::System.String value);
        partial void OnimagenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_creaccion
        {
            get
            {
                return _fecha_creaccion;
            }
            set
            {
                Onfecha_creaccionChanging(value);
                ReportPropertyChanging("fecha_creaccion");
                _fecha_creaccion = StructuralObject.SetValidValue(value, "fecha_creaccion");
                ReportPropertyChanged("fecha_creaccion");
                Onfecha_creaccionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_creaccion;
        partial void Onfecha_creaccionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_creaccionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kosmozbusModel", "trabajador_ibfk_1", "departamento")]
        public departamento departamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<departamento>("kosmozbusModel.trabajador_ibfk_1", "departamento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<departamento>("kosmozbusModel.trabajador_ibfk_1", "departamento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<departamento> departamentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<departamento>("kosmozbusModel.trabajador_ibfk_1", "departamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<departamento>("kosmozbusModel.trabajador_ibfk_1", "departamento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kosmozbusModel", "usuario_ibfk_1", "usuario")]
        public EntityCollection<usuario> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("kosmozbusModel.usuario_ibfk_1", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("kosmozbusModel.usuario_ibfk_1", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kosmozbusModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static usuario Createusuario(global::System.Int32 id)
        {
            usuario usuario = new usuario();
            usuario.id = id;
            return usuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idtrabajadorfk
        {
            get
            {
                return _idtrabajadorfk;
            }
            set
            {
                OnidtrabajadorfkChanging(value);
                ReportPropertyChanging("idtrabajadorfk");
                _idtrabajadorfk = StructuralObject.SetValidValue(value, "idtrabajadorfk");
                ReportPropertyChanged("idtrabajadorfk");
                OnidtrabajadorfkChanged();
            }
        }
        private Nullable<global::System.Int32> _idtrabajadorfk;
        partial void OnidtrabajadorfkChanging(Nullable<global::System.Int32> value);
        partial void OnidtrabajadorfkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario1
        {
            get
            {
                return _usuario1;
            }
            set
            {
                Onusuario1Changing(value);
                ReportPropertyChanging("usuario1");
                _usuario1 = StructuralObject.SetValidValue(value, true, "usuario1");
                ReportPropertyChanged("usuario1");
                Onusuario1Changed();
            }
        }
        private global::System.String _usuario1;
        partial void Onusuario1Changing(global::System.String value);
        partial void Onusuario1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, true, "contrasena");
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, true, "estatus");
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_creaccion
        {
            get
            {
                return _fecha_creaccion;
            }
            set
            {
                Onfecha_creaccionChanging(value);
                ReportPropertyChanging("fecha_creaccion");
                _fecha_creaccion = StructuralObject.SetValidValue(value, "fecha_creaccion");
                ReportPropertyChanged("fecha_creaccion");
                Onfecha_creaccionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_creaccion;
        partial void Onfecha_creaccionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_creaccionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kosmozbusModel", "usuario_ibfk_1", "trabajador")]
        public trabajador trabajador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<trabajador>("kosmozbusModel.usuario_ibfk_1", "trabajador").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<trabajador>("kosmozbusModel.usuario_ibfk_1", "trabajador").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<trabajador> trabajadorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<trabajador>("kosmozbusModel.usuario_ibfk_1", "trabajador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<trabajador>("kosmozbusModel.usuario_ibfk_1", "trabajador", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
