//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public municipio()
        {
            this.cps = new HashSet<cp>();
        }
    
        public int clavem { get; set; }
        public Nullable<int> clavecfk { get; set; }
        public string nombrem { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual ICollection<cp> cps { get; set; }
    }
}
